import turtle as t

def smile(x,y,z):
    #脸
    t.pensize(3)
    t.speed(0)
    t.penup()
    t.goto(x,y)
    t.fillcolor('yellow')
    t.begin_fill()
    t.pendown()
    t.pencolor('orange')
    t.circle(z)
    t.end_fill()

    #嘴笑
    t.pencolor('brown')
    t.setheading(90)
    t.penup()
    t.forward(z/3)
    t.setheading(0)
    t.pendown()
    t.circle(z * 2 / 3, 60)
    t.circle(z * 2 / 3, -120)
    t.circle(z * 2 / 3, 60)

    #右眼
    t.penup()
    t.setheading(90)
    t.forward(z)
    t.setheading(0)
    t.forward(z/3)
    t.pendown()
    t.fillcolor('white')
    t.begin_fill()
    t.circle(z*2/15)
    t.end_fill()
    t.pencolor('black')
    t.fillcolor('black')
    t.begin_fill()
    t.circle(z/10)
    t.end_fill()

    #左眼
    t.pencolor('brown')
    t.penup()
    t.setheading(180)
    t.forward(z*2/3)
    t.pendown()
    t.fillcolor('white')
    t.begin_fill()
    t.setheading(0)
    t.circle(z*2/15)
    t.end_fill()
    t.pencolor('black')
    t.fillcolor('black')
    t.begin_fill()
    t.circle(z/10)
    t.end_fill()
    t.hideturtle()

def weep(x,y,z):
    #脸
    t.pensize(3)
    t.speed(0)
    t.penup()
    t.goto(x,y)
    t.fillcolor('yellow')
    t.begin_fill()
    t.pendown()
    t.pencolor('orange')
    t.circle(z)
    t.end_fill()

    #嘴笑
    t.pencolor('brown')
    t.setheading(90)
    t.penup()
    t.forward(z*2/3)
    t.setheading(0)
    t.pendown()
    t.setheading(180)
    t.circle(z * 2 / 3, 60)
    t.circle(z * 2 / 3, -120)
    t.circle(z * 2 / 3, 60)

    #右眼
    t.penup()
    t.setheading(90)
    t.forward(z*2/3)
    t.setheading(0)
    t.forward(z/3)
    t.pendown()
    t.fillcolor('white')
    t.begin_fill()
    t.circle(z*2/15)
    t.end_fill()
    t.pencolor('black')
    t.fillcolor('black')
    t.begin_fill()
    t.circle(z/10)
    t.end_fill()

    #左眼
    t.pencolor('brown')
    t.penup()
    t.setheading(180)
    t.forward(z*2/3)
    t.pendown()
    t.fillcolor('white')
    t.begin_fill()
    t.setheading(0)
    t.circle(z*2/15)
    t.end_fill()
    t.pencolor('black')
    t.fillcolor('black')
    t.begin_fill()
    t.circle(z/10)
    t.end_fill()
    t.hideturtle()


smile(0,-100,200)
smile(-200,-300,100)
smile(200,-200,150)
t.done()