# Generated by Django 4.0.6 on 2022-07-05 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FilmInfo',
            fields=[
                ('fid', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PeopleInfo',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('uname', models.CharField(max_length=20)),
                ('gender', models.BooleanField()),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film.filminfo')),
            ],
        ),
    ]
